#!/bin/bash
# Regenerate assets.js from source JPGs in assets/.
#
# Output: assets.js exports window.WITTY_ASSETS = { "<name>": "data:image/jpeg;base64,..." }
# Consumed by Claude artifacts where img-src CSP blocks external CDNs — data: URIs work.
#
# Requires: ImageMagick (magick), coreutils base64.

set -e
cd "$(dirname "$0")"

TMP=$(mktemp -d)
trap "rm -rf $TMP" EXIT

# Avatars: 160×160 square, quality 80
for name in avatar-annemarie avatar-michel; do
  magick "assets/$name.jpg" -resize 160x160^ -gravity center -extent 160x160 -quality 80 -strip "$TMP/$name.jpg"
done

# Placeholder images: max 800px, quality 72
for name in hotspot-image media-carousel tekst-image tekst-video-thumb; do
  magick "assets/$name.jpg" -resize '800x800>' -quality 72 -strip "$TMP/$name.jpg"
done

# External link thumb: 400×300, quality 75
magick "assets/external-link-thumb.jpg" -resize '400x300^' -gravity center -extent 400x300 -quality 75 -strip "$TMP/external-link-thumb.jpg"

# Vraag images: 600×400, quality 75
for name in vraag-img-1 vraag-img-2; do
  magick "assets/$name.jpg" -resize '600x400^' -gravity center -extent 600x400 -quality 75 -strip "$TMP/$name.jpg"
done

{
  echo '// Auto-generated by build-assets.sh — do not edit by hand.'
  echo '// Base64-encoded versions of assets/*.jpg for Claude artifact use.'
  echo '// Claude img-src CSP blocks external CDNs; data: URIs are allowed.'
  echo 'window.WITTY_ASSETS = {'
  for file in "$TMP"/*.jpg; do
    name=$(basename "$file" .jpg)
    b64=$(base64 < "$file" | tr -d '\n')
    echo "  \"$name\": \"data:image/jpeg;base64,$b64\","
  done
  echo '};'
} > assets.js

echo "Wrote $(du -h assets.js | cut -f1) assets.js with $(grep -c 'data:image' assets.js) entries."
