#!/bin/bash
# Build colors_and_type_artifact.css: same tokens as colors_and_type.css but
# with Atkinson Hyperlegible Next inlined as base64 woff2 data: URIs.
#
# Why: claude.ai artifact font-src CSP may not always allow fonts.gstatic.com.
# data: URIs are universally allowed under any reasonable font-src directive.
# Lexend stays as a Google Fonts @import (graceful fallback to system-ui).
#
# Requires: Python 3 with fontTools + brotli (pip3 install fonttools brotli).

set -e
cd "$(dirname "$0")"

TMP=$(mktemp -d)
trap "rm -rf $TMP" EXIT

# 1. Convert TTFs → woff2 (smaller; brotli-compressed inside)
for ttf in fonts/AtkinsonHyperlegibleNext-*.ttf; do
  base=$(basename "$ttf" .ttf)
  python3 -c "
from fontTools.ttLib import TTFont
f = TTFont('$ttf')
f.flavor = 'woff2'
f.save('$TMP/$base.woff2')
"
done

# 2. Build CSS with inline base64 @font-face rules
declare -a entries=(
  "200 normal ExtraLight"
  "200 italic  ExtraLightItalic"
  "300 normal Light"
  "300 italic  LightItalic"
  "400 normal Regular"
  "400 italic  Italic"
  "500 normal Medium"
  "500 italic  MediumItalic"
  "600 normal SemiBold"
  "600 italic  SemiBoldItalic"
  "700 normal Bold"
  "700 italic  BoldItalic"
  "800 normal ExtraBold"
  "800 italic  ExtraBoldItalic"
)

{
  echo "/* Auto-generated by build-artifact-css.sh — do not edit by hand."
  echo "   Same tokens as colors_and_type.css but with Atkinson Hyperlegible Next"
  echo "   embedded as base64 woff2 data: URIs. Use this variant in claude.ai"
  echo "   artifacts where font-src may not include fonts.gstatic.com.   */"
  echo ""
  echo "@import url('https://fonts.googleapis.com/css2?family=Lexend:wght@400;500;600;700&display=swap');"
  echo ""
  for entry in "${entries[@]}"; do
    weight=$(echo "$entry" | awk '{print $1}')
    style=$(echo "$entry" | awk '{print $2}')
    base=$(echo "$entry" | awk '{print $3}')
    b64=$(base64 < "$TMP/AtkinsonHyperlegibleNext-$base.woff2" | tr -d '\n')
    echo "@font-face { font-family: 'Atkinson Hyperlegible Next'; font-style: $style; font-weight: $weight; src: url(data:font/woff2;base64,$b64) format('woff2'); }"
  done
  echo ""
  sed -n '/^:root/,$p' colors_and_type.css
} > colors_and_type_artifact.css

echo "Wrote $(du -h colors_and_type_artifact.css | cut -f1) colors_and_type_artifact.css ($(grep -c '@font-face' colors_and_type_artifact.css) @font-face rules)."
